### ISSUE TITLE
comment déclarer le moteur  ?

### ISSUE THREAD

**Issue by jfpace** [AriiPortal/ATSBundle#3]
Hello Eric,

On fait un peu de com sur le module ATS.
En lisant le readme on voit comment déclarer la base de données mais pas comment déclarer le moteur pour communiquer avec et par exemple tuer une taches problématique.
Il est indiqué SSH ou Web Services pour le mode de comm c'est tout.

jf

**Comment by AriiPortal** [comment]
Les web services Autosys sont apparus en version 11.0 puis ont disparus jusqu'à la version 11.3.6 qui est actuellement la dernière. Deux questions se posent actuellement: sont-ils pérennes et couvrent-ils les mêmes fonctions que le client ?
En attendant, le ssh permet d'accéder aux clients Autosys sans installation sur le portail, la configuration est donc la même que pour les autres moteurs, par exemple:

```
    spoolers:
        -
            name: 'Autosys Test'
            type: waae
            0:
                shell:
                    cmd: ssh
                    user: autosys
                    host: (ma_machine)
                    key: (ma_cle)
                    data:  (équivalent $AUTOSYS)
                    home: (équivalent $AUTOUSER)
```

Je mets à jour la configuration dés que les réponses de la partie web services se précisent.
